const catalogHtml = [
  {
    "projectName": "SmartDevice",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "smartdevice-desktop.png",
    "img2x": "",
    "imgTypeWebp1x": "smartdevice-desktop.webp",
    "imgTypeWebp2x": "",
    "imgAlt": "превью сайта SmartDevice",
    "projectLink": "#",
    "projectGithubLink": "#",
    "projectDesc": "Удаленная стажировка - Акселератор HTML Academy. Работа по техническому заданию и с критериями качества",
  },
  {
    "projectName": "Велосипеды",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "bikes-tablet.jpg",
    "img2x": "bikes-tablet@2x.jpg",
    "imgTypeWebp1x": "bikes-tablet.webp",
    "imgTypeWebp2x": "bikes-tablet@2x.webp",
    "imgAlt": "превью сайта велосипедов",
    "projectLink": "https://askomarov.github.io/bicycle/",
    "projectGithubLink": "https://github.com/askomarov/bicycle",
    "projectDesc": "Проект выполнен в рамках обучения работе в команде - Акселератор HTML Academy. Работа по техническому заданию с критериями качества, с использованием сборки Лиги А",
  },
  {
    "projectName": "Путешествия",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "komarov-way-2.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": "komarov-way-2.webp",
    "imgTypeWebp2x": undefined,
    "imgAlt": "Превью сайт о путешествиях",
    "projectLink": "https://askomarov.github.io/komarov_way/",
    "projectGithubLink": "https://github.com/askomarov/komarov_way",
    "projectDesc": "Адаптивная страница. С использованием gulp, препроцессоров, адаптивных изображений. Не много JavaScript",
  },
  {
    "projectName": "Попутчики",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "img-pognali@1xdesktop.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": "img-pognali@1xdesktop.webp",
    "imgTypeWebp2x": undefined,
    "imgAlt": "Превью сайт попутчиков для путешествий",
    "projectLink": "https://askomarov.github.io/pognaliHtmlAcademy/",
    "projectGithubLink": "https://github.com/askomarov/pognaliHtmlAcademy",
    "projectDesc": "Адаптивный трех-страничный сайт, с огромным количеством трудоемких элементов, оживленный с помощью JavaScript. С использованием gulp, препроцессоров, адаптивных изображений",
  },
  {
    "projectName": "Рукоделие",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "mishka-preview.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": "mishka-preview.webp",
    "imgTypeWebp2x": undefined,
    "imgAlt": "Превью сайт вязанные вещи ручной работы",
    "projectLink": "https://askomarov.github.io/mishka/",
    "projectGithubLink": "https://github.com/askomarov/mishka",
    "projectDesc": "Адаптивный трех-страничный mobile-first сайт. С использованием сборки gulp, препроцессора Sass.Не много JavaScript",
  },
  {
    "projectName": "Корм для кошек",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "img-catenergy.jpg",
    "img2x": "img-catenergy@2x.jpg",
    "imgTypeWebp1x": "img-catenergy.webp",
    "imgTypeWebp2x": "img-catenergy@2x.webp",
    "imgAlt": "Превью сайт питание для кошек",
    "projectLink": "https://askomarov.github.io/CatFromAcademy/index.html",
    "projectGithubLink": "https://github.com/askomarov/CatFromAcademy",
    "projectDesc": "Адаптивный трех-страничный сайт. С использованием gulp, препроцессоров, адаптивных изображений",
  },
  {
    "projectName": "Магазин мороженого",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "img-gllacy.jpg",
    "img2x": "img-gllacy@2x.jpg",
    "imgTypeWebp1x": "img-gllacy.webp",
    "imgTypeWebp2x": "img-gllacy@2x.webp",
    "imgAlt": "Превью сайта мороженного",
    "projectLink": "https://askomarov.github.io/1422707-gllacy-29/",
    "projectGithubLink": "https://github.com/askomarov/1422707-gllacy-29",
    "projectDesc": "Двустраничный, неадаптивный, но красочный сайт",
  },
  {
    "projectName": "Туристический город",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "img-sedona.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": "img-sedona.webp",
    "imgTypeWebp2x": undefined,
    "imgAlt": "превью сайта для туристов города Sedona",
    "projectLink": "https://askomarov.github.io/mySedonaByHtmlAcademy/",
    "projectGithubLink": "https://github.com/askomarov/mySedonaByHtmlAcademy",
    "projectDesc": "Адаптивный трех-страничный сайт. С использованием gulp, препроцессоров",
  },
  {
    "projectName": "Элементы форм",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "img-city.jpg",
    "img2x": "img-city@2x.jpg",
    "imgTypeWebp1x": "img-city.webp",
    "imgTypeWebp2x": "img-city@2x.webp",
    "imgAlt": "Превью пример стилизации элементов форм",
    "projectLink": "https://askomarov.github.io/filter/",
    "projectGithubLink": "https://github.com/askomarov/filter",
    "projectDesc": "Пример списка товаров с кастомными элементами формы",
  }
];

const catalogJs = [
  {
    "projectName": "Кекстаграм",
    "classActive": false,
    "dataFilter": "javascript",
    "img": "kekstagram.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": undefined,
    "imgTypeWebp2x": undefined,
    "imgAlt": "Превью сайт почти инстаграмм",
    "projectLink": "https://askomarov.github.io/kekstagramByHTMLAcademy/",
    "projectGithubLink": "https://github.com/askomarov/kekstagramByHTMLAcademy",
    "projectDesc": "Учебная работа с онлайн-курса по JavaScript - подобронее в репозитории",
  },
  {
    "projectName": "Кексобукинг",
    "classActive": false,
    "dataFilter": "javascript",
    "img": "keksobooking.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": undefined,
    "imgTypeWebp2x": undefined,
    "imgAlt": "Превью Кексобукинг поиск жилья в Токио",
    "projectLink": "https://askomarov.github.io/keksobookingByHTMLAcademy/",
    "projectGithubLink": "https://github.com/askomarov/keksobookingByHTMLAcademy",
    "projectDesc": "Учебная работа с онлайн-курса по JavaScript - подобронее в репозитории",
  }
];

export { catalogHtml, catalogJs };
