const catalogHtml = [
  {
    "projectName": "pognali",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "img-pognali@1xdesktop.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": "img-pognali@1xdesktop.webp",
    "imgTypeWebp2x": undefined,
    "imgAlt": "Превью сайт попутчиков для путешествий",
    "projectLink": "https://askomarov.github.io/pognaliHtmlAcademy/",
    "projectGithubLink": "https://github.com/askomarov/pognaliHtmlAcademy",
    "projectDesc": "Адаптивный трех-страничный сайт, с огромным количеством трудоемких элементов, оживленный с помощью JavaScript. С использованием gulp, препроцессоров, адаптивных изображений",
  },
  {
    "projectName": "komarov-way",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "komarov-way-2.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": undefined,
    "imgTypeWebp2x": undefined,
    "imgAlt": "Превью сайт о путешествиях",
    "projectLink": "https://askomarov.github.io/komarov_way/",
    "projectGithubLink": "https://github.com/askomarov/komarov_way",
    "projectDesc": "Адаптивная страница. С использованием gulp, препроцессоров,адаптивных изображений. Не много JavaScript",
  },
  {
    "projectName": "mishka",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "mishka-preview.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": undefined,
    "imgTypeWebp2x": undefined,
    "imgAlt": "Превью сайт вязанные вещи ручной работы",
    "projectLink": "https://askomarov.github.io/mishka/",
    "projectGithubLink": "https://github.com/askomarov/mishka",
    "projectDesc": "Адаптивный трех-страничный mobile-first сайт. С использованием сборки gulp, препроцессора Sass.Не много JavaScript",
  },
  {
    "projectName": "catenergy",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "img-catenergy.jpg",
    "img2x": "img-catenergy@2x.jpg",
    "imgTypeWebp1x": "img-catenergy.webp",
    "imgTypeWebp2x": "img-catenergy@2x.webp",
    "imgAlt": "Превью сайт питание для кошек",
    "projectLink": "https://askomarov.github.io/CatFromAcademy/index.html",
    "projectGithubLink": "https://github.com/askomarov/CatFromAcademy",
    "projectDesc": "Адаптивный трех-страничный сайт. С использованием gulp, препроцессоров, адаптивных изображений",
  },
  {
    "projectName": "gllacy",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "img-gllacy.jpg",
    "img2x": "img-gllacy@2x.jpg",
    "imgTypeWebp1x": "img-gllacy.webp",
    "imgTypeWebp2x": "img-gllacy@2x.webp",
    "imgAlt": "Превью сайта мороженного",
    "projectLink": "https://askomarov.github.io/1422707-gllacy-29/",
    "projectGithubLink": "https://github.com/askomarov/1422707-gllacy-29",
    "projectDesc": "Двустраничный, неадаптивный, но красочный сайт",
  },
  {
    "projectName": "sedona",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "img-sedona.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": "img-sedona.webp",
    "imgTypeWebp2x": undefined,
    "imgAlt": "превью сайта для туристов города Sedona",
    "projectLink": "https://askomarov.github.io/mySedonaByHtmlAcademy/",
    "projectGithubLink": "https://github.com/askomarov/mySedonaByHtmlAcademy",
    "projectDesc": "Адаптивный трех-страничный сайт. С использованием gulp, препроцессоров",
  },
  {
    "projectName": "example form",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "img-city.jpg",
    "img2x": "img-city@2x.jpg",
    "imgTypeWebp1x": "img-city.webp",
    "imgTypeWebp2x": undefined,
    "imgAlt": "Превью пример стилизации элементов форм",
    "projectLink": "https://askomarov.github.io/filter/",
    "projectGithubLink": "https://github.com/askomarov/filter",
    "projectDesc": "Пример списка товаров с кастомными элементами формы",
  }
  // {
  //   "projectName": "",
  //   "classActive": true,
  //   "dataFilter": "html-css",
  //   "img": "",
  //   "imgTypeWebp1x": "",
  //   "imgAlt": "",
  //   "projectLink": "",
  //   "projectGithubLink": "",
  // },
];

const catalogJs = [
  {
    "projectName": "kekstgramm",
    "classActive": false,
    "dataFilter": "javascript",
    "img": "kekstagram.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": undefined,
    "imgTypeWebp2x": undefined,
    "imgAlt": "Превью сайт почти инстаграмм",
    "projectLink": "https://askomarov.github.io/kekstagramByHTMLAcademy/",
    "projectGithubLink": "https://github.com/askomarov/kekstagramByHTMLAcademy", "projectDesc": "Учебная работа с онлайн-курса по JavaScript",
  },
  {
    "projectName": "keksobooking",
    "classActive": false,
    "dataFilter": "javascript",
    "img": "keksobooking.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": undefined,
    "imgTypeWebp2x": undefined,
    "imgAlt": "Превью Кексобукинг поиск жилья в Токио",
    "projectLink": "https://askomarov.github.io/keksobookingByHTMLAcademy/",
    "projectGithubLink": "https://github.com/askomarov/keksobookingByHTMLAcademy",
    "projectDesc": "Учебная работа с онлайн-курса по JavaScript",
  }
];

export { catalogHtml, catalogJs };
