const catalogHtml = [
  {
    "projectName": "Jewellery",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "askomarov-jewellery3.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": "askomarov-jewellery3.webp",
    "imgTypeWebp2x": undefined,
    "imgAlt": "превью сайта Jewellery",
    "projectLink": "https://askomarov.github.io/jewellery3/main.html",
    "projectGithubLink": "https://github.com/askomarov/jewellery3",
    "projectDesc": "Remote Internship - HTML Academy Accelerator. Work according to the terms of reference and with quality criteria. Slider Swiper.js",
  },
  {
    "projectName": "SmartDevice",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "welcome.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": "smartdevice-desktop.webp",
    "imgTypeWebp2x": undefined,
    "imgAlt": "превью сайта SmartDevice",
    "projectLink": "https://askomarov.github.io/smart-device/",
    "projectGithubLink": "https://github.com/askomarov/smart-device",
    "projectDesc": "Remote Internship - HTML Academy Accelerator. Work according to the terms of reference and with quality criteria. Modal window of the feedback form.",
  },
  {
    "projectName": "Bicycle shop",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "bikes-tablet.jpg",
    "img2x": "bikes-tablet@2x.jpg",
    "imgTypeWebp1x": "bikes-tablet.webp",
    "imgTypeWebp2x": "bikes-tablet@2x.webp",
    "imgAlt": "превью сайта велосипедов",
    "projectLink": "https://askomarov.github.io/bicycle/",
    "projectGithubLink": "https://github.com/askomarov/bicycle",
    "projectDesc": "Remote Internship - HTML Academy Accelerator. Super simple page, responsive, desktop first.",
  },
  {
    "projectName": "Ways to travel",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "komarov-way-2.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": "komarov-way-2.webp",
    "imgTypeWebp2x": undefined,
    "imgAlt": "Превью сайт о путешествиях",
    "projectLink": "https://askomarov.github.io/komarov_way/",
    "projectGithubLink": "https://github.com/askomarov/komarov_way",
    "projectDesc": "responsive page. Using gulp, preprocessor scss, adaptive images (picture + webp). A little JavaScript - modal and validate form, tapbar.",
  },
  {
    "projectName": "Fellow travelers",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "img-pognali@1xdesktop.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": "img-pognali@1xdesktop.webp",
    "imgTypeWebp2x": undefined,
    "imgAlt": "Превью сайт попутчиков для путешествий",
    "projectLink": "https://askomarov.github.io/pognaliHtmlAcademy/",
    "projectGithubLink": "https://github.com/askomarov/pognaliHtmlAcademy",
    "projectDesc": "An adaptive three-page website, with a huge number of time-consuming elements, animated with JavaScript, burger menu, accordion, modal etc.. Using gulp, scss preprocessor, adaptive images.",
  },
  {
    "projectName": "Needlework",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "mishka-preview.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": "mishka-preview.webp",
    "imgTypeWebp2x": undefined,
    "imgAlt": "Превью сайт вязанные вещи ручной работы",
    "projectLink": "https://askomarov.github.io/mishka/",
    "projectGithubLink": "https://github.com/askomarov/mishka",
    "projectDesc": "Adaptive three-page mobile-first website. Using the gulp, the Sass preprocessor. A little JavaScript.",
  },
  {
    "projectName": "Cat food",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "img-catenergy.jpg",
    "img2x": "img-catenergy@2x.jpg",
    "imgTypeWebp1x": "img-catenergy.webp",
    "imgTypeWebp2x": "img-catenergy@2x.webp",
    "imgAlt": "Превью сайт питание для кошек",
    "projectLink": "https://askomarov.github.io/CatFromAcademy/index.html",
    "projectGithubLink": "https://github.com/askomarov/CatFromAcademy",
    "projectDesc": "Adaptive three-page website. Using gulp, css preprocessor, adaptive images.",
  },
  {
    "projectName": "Ice Cream Shop",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "img-gllacy.jpg",
    "img2x": "img-gllacy@2x.jpg",
    "imgTypeWebp1x": "img-gllacy.webp",
    "imgTypeWebp2x": "img-gllacy@2x.webp",
    "imgAlt": "Превью сайта мороженного",
    "projectLink": "https://askomarov.github.io/1422707-gllacy-29/",
    "projectGithubLink": "https://github.com/askomarov/1422707-gllacy-29",
    "projectDesc": "A two-page, non-adaptive, but colorful website with catalog. A little JavaScript. Stylized form elements.",
  },
  {
    "projectName": "Tourist city",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "img-sedona.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": "img-sedona.webp",
    "imgTypeWebp2x": undefined,
    "imgAlt": "превью сайта для туристов города Sedona",
    "projectLink": "https://askomarov.github.io/mySedonaByHtmlAcademy/",
    "projectGithubLink": "https://github.com/askomarov/mySedonaByHtmlAcademy",
    "projectDesc": "Adaptive three-page website. Using gulp, scss preprocessor",
  },
  {
    "projectName": "Catalog with stylized form elements",
    "classActive": true,
    "dataFilter": "html-css",
    "img": "img-city.jpg",
    "img2x": "img-city@2x.jpg",
    "imgTypeWebp1x": "img-city.webp",
    "imgTypeWebp2x": "img-city@2x.webp",
    "imgAlt": "Превью пример стилизации элементов форм",
    "projectLink": "https://askomarov.github.io/filter/",
    "projectGithubLink": "https://github.com/askomarov/filter",
    "projectDesc": "Example of a catalog with stylized form elements",
  }
];

const catalogJs = [
  {
    "projectName": "Kekstagram",
    "classActive": false,
    "dataFilter": "javascript",
    "img": "kekstagram.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": "kekstagram.webp",
    "imgTypeWebp2x": undefined,
    "imgAlt": "Превью сайт почти инстаграмм",
    "projectLink": "https://askomarov.github.io/kekstagramByHTMLAcademy/",
    "projectGithubLink": "https://github.com/askomarov/kekstagramByHTMLAcademy",
    "projectDesc": "Study work from an online course on JavaScript - more info in the repository",
  },
  {
    "projectName": "Keksobooking",
    "classActive": false,
    "dataFilter": "javascript",
    "img": "keksobooking.jpg",
    "img2x": undefined,
    "imgTypeWebp1x": "keksobooking.webp",
    "imgTypeWebp2x": undefined,
    "imgAlt": "Превью Кексобукинг поиск жилья в Токио",
    "projectLink": "https://askomarov.github.io/keksobookingByHTMLAcademy/",
    "projectGithubLink": "https://github.com/askomarov/keksobookingByHTMLAcademy",
    "projectDesc": "Study work from an online course on JavaScript - more info in the repository",
  }
];

export { catalogHtml, catalogJs };
